'use strict';
window.BibleMeta=(()=>{
  let connection;
  function db(){return connection||=new Promise((resolve,reject)=>{const request=indexedDB.open('bible-qsse-meta',1);request.onupgradeneeded=()=>{const store=request.result.createObjectStore('documents',{keyPath:'id'});store.createIndex('library','library')};request.onsuccess=()=>resolve(request.result);request.onerror=()=>{connection=null;reject(request.error)}})}
  async function records(library){const database=await db();return new Promise((resolve,reject)=>{const request=database.transaction('documents').objectStore('documents').index('library').getAll(library);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
  async function put(record){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('documents','readwrite');tx.objectStore('documents').put(record);tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error);tx.onerror=()=>reject(tx.error)})}
  async function update(library,path,changes){const current=(await records(library)).find(record=>record.path===path)||{id:[library,path],library,path,favorite:false,lastOpened:0};const next={...current,...changes,id:[library,path],library,path};await put(next);return next}
  return {load:async library=>new Map((await records(library)).map(record=>[record.path,record])),favorite:(library,path,value)=>update(library,path,{favorite:!!value}),opened:(library,path,info)=>update(library,path,{...info,lastOpened:Date.now()}),remove:async(library,path)=>{const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('documents','readwrite');tx.objectStore('documents').delete([library,path]);tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error);tx.onerror=()=>reject(tx.error)})},export:records,merge:async(library,items)=>{const existing=new Map((await records(library)).map(record=>[record.path,record]));for(const source of items||[]){const current=existing.get(source.path);await put({...source,...current,id:[library,source.path],library,path:source.path,favorite:!!(source.favorite||current?.favorite),lastOpened:Math.max(source.lastOpened||0,current?.lastOpened||0)})}}};
})();
