const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {JSDOM}=require('jsdom');const {indexedDB}=require('fake-indexeddb');
const rootPath=path.resolve(__dirname,'..');
const dirs=new Map();
class Dir{constructor(id,name,children=[]){this._testDirId=id;this.name=name;this.kind='directory';this.children=children;this.permissionState='granted';this.permissionRequests=0;dirs.set(id,this)}async *entries(){for(const child of this.children)yield [child.name,child]}async queryPermission(){return this.permissionState}async requestPermission(){this.permissionRequests++;this.permissionState='granted';return 'granted'}async isSameEntry(other){return this._testDirId===other._testDirId}async removeEntry(name,{recursive=false}={}){const index=this.children.findIndex(child=>child.name===name);if(index<0)throw new DOMException('Absent','NotFoundError');const target=this.children[index];if(target.kind==='directory'&&target.children.length&&!recursive)throw new DOMException('Non vide','InvalidModificationError');this.children.splice(index,1)}}
class FileHandle{constructor(name,contents){this.name=name;this.kind='file';this.contents=contents;this.modified=1}async getFile(){return {name:this.name,size:this.contents.length,lastModified:this.modified,arrayBuffer:async()=>new TextEncoder().encode(this.contents).buffer}}}
const manual=new FileHandle('manuel.pdf','Page une.\nProcédure evacuation et sécurité incendie.'),scan=new FileHandle('scan.pdf','');
const primary=new Dir('one','Bible QSSE',[new Dir('fire','02 - Incendie',[manual,new Dir('sub','Formation',[scan]),new Dir('empty','Dossier vide',[])]),new Dir('security','04 - Sûreté',[new FileHandle('plan.pdf','Plan de sûreté')])]);
const other=new Dir('two','Bible QSSE',[new Dir('health','03 - Santé',[new FileHandle('manuel.pdf','Autre bibliothèque')])]);
const nativeClone=global.structuredClone;
global.structuredClone=value=>{const clone=nativeClone(value);const restore=v=>{if(v&&typeof v==='object'){if(v._testDirId)return dirs.get(v._testDirId);for(const k of Object.keys(v))v[k]=restore(v[k])}return v};return restore(clone)};
const wait=async(fn)=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,10))}throw new Error('Timed out')};
function app(){const dom=new JSDOM(fs.readFileSync(path.join(rootPath,'index.html'),'utf8'),{url:'https://example.test/Bible-QSSE/',runScripts:'outside-only'});const w=dom.window;w.indexedDB=indexedDB;w.matchMedia=()=>({matches:false});w.showDirectoryPicker=async()=>primary;w.confirm=()=>true;w.scrollTo=()=>{};w.requestAnimationFrame=callback=>{callback();return 1};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.BiblePDF={engine:async()=>({extractText:async(bytes,progress)=>{progress(1,1);return new TextDecoder().decode(bytes).split('\n')}}),open:async(file,options)=>{w.lastOpened={file,options};options.onPage?.(options.startPage)}};for(const script of ['local-tags.js','library-meta.js','pdf-store.js','app.js'])w.eval(fs.readFileSync(path.join(rootPath,script),'utf8'));return dom}
test('library flow: tags, list, content indexing, page navigation and persistence',async()=>{
 let dom=app(),w=dom.window,d=w.document,backup;
 try{
  await wait(()=>d.querySelector('.empty'));d.querySelector('#choose').click();await wait(()=>d.querySelectorAll('.categoryCard').length===2);assert.ok([...d.querySelectorAll('.categoryCard')].some(card=>card.style.getPropertyValue('--category')==='#e5484d'));d.querySelector('.categoryCard .openDoc').click();await wait(()=>d.querySelectorAll('.card').length===3);[...d.querySelectorAll('.card')].find(card=>card.querySelector('.name').textContent==='Dossier vide').querySelector('.deleteEntry').click();await wait(()=>d.querySelectorAll('.card').length===2);
  d.querySelector('#listView').click();await wait(()=>[...d.querySelectorAll('.grid.list .meta')].some(el=>el.textContent.includes('o')));assert.equal(d.querySelector('#listView').getAttribute('aria-pressed'),'true');d.querySelector('#sortBy').value='size';d.querySelector('#sortBy').dispatchEvent(new w.Event('change'));d.querySelector('#sortDirection').click();await wait(()=>d.querySelector('#sortDirection').textContent==='↓'&&d.querySelector('.card .name'));assert.equal(d.querySelector('.card .name').textContent,'Formation','folders stay before PDF files regardless of sort');assert.equal(w.localStorage.getItem('bible-qsse-sort'),'size');assert.equal(w.localStorage.getItem('bible-qsse-sort-direction'),'desc');
  const favoriteCard=[...d.querySelectorAll('.card')].find(card=>card.querySelector('.name').textContent==='manuel.pdf'),sameNode=favoriteCard.querySelector('.favoriteToggle');sameNode.click();await wait(()=>sameNode.getAttribute('aria-pressed')==='true');assert.equal(favoriteCard.querySelector('.favoriteToggle'),sameNode,'favoriting updates the existing card without rerendering the list');
  d.querySelector('.tagEdit:not(.deleteEntry)').click();d.querySelector('#tagInput').value='Incendie, SUVA, incendie';d.querySelector('#tagForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait(()=>d.querySelectorAll('.tagChip').length===2);
  d.querySelector('#quickFilter').value='pdf';d.querySelector('#quickFilter').dispatchEvent(new w.Event('input'));await wait(()=>d.querySelectorAll('.card').length===2);const selectButton=[...d.querySelectorAll('.openDoc')].find(button=>button.querySelector('.name').textContent==='manuel.pdf'),down=new w.Event('pointerdown',{bubbles:true});Object.defineProperties(down,{pointerType:{value:'touch'},button:{value:0},clientX:{value:10},clientY:{value:10}});selectButton.dispatchEvent(down);await new Promise(resolve=>setTimeout(resolve,570));assert.equal(d.querySelector('#selectionBar').hidden,false);selectButton.click();[...d.querySelectorAll('.openDoc')].find(button=>button.querySelector('.name').textContent==='scan.pdf').click();assert.match(d.querySelector('#selectionCount').textContent,/2/);d.querySelector('#selectTag').value='suva';d.querySelector('#selectApplyTag').click();await wait(()=>d.querySelectorAll('.tagChip').length===3);d.querySelector('#selectCancel').click();d.querySelector('#quickFilter').value='';d.querySelector('#quickFilter').dispatchEvent(new w.Event('input'));await wait(()=>d.querySelectorAll('.card').length===2);
  d.querySelector('#indexPdfs').click();await wait(()=>d.querySelector('#indexStatus').textContent.includes('OCR nécessaire'));
  d.querySelector('#categoryFilter').value='Incendie';d.querySelector('#categoryFilter').dispatchEvent(new w.Event('change'));d.querySelector('#tagFilter').value='suva';d.querySelector('#tagFilter').dispatchEvent(new w.Event('change'));d.querySelector('#favoriteFilter').checked=true;d.querySelector('#favoriteFilter').dispatchEvent(new w.Event('change'));
  d.querySelector('#quickFilter').value='evacuation';d.querySelector('#quickFilter').dispatchEvent(new w.Event('input'));
  await new Promise(resolve=>setTimeout(resolve,180));assert.ok(d.querySelector('#status').textContent.startsWith('0 résultat'),d.querySelector('#status').textContent);assert.equal(d.querySelector('#search').value,'','the quick filter does not silently search indexed PDF text');
  d.querySelector('#contentSearch').click();await wait(()=>d.querySelector('#status').textContent.startsWith('1 résultat'));assert.match(d.querySelector('.searchExcerpt').textContent,/page 2/);
  d.querySelector('.openDoc').click();await wait(()=>w.lastOpened);assert.equal(w.lastOpened.options.startPage,2);assert.equal(w.lastOpened.options.searchQuery,'evacuation');
  d.querySelector('#pdfClose')?.click();assert.match(d.querySelector('#resumeOpen').textContent,/manuel\.pdf — page 2/);d.querySelector('#showFavorites').click();await wait(()=>d.querySelector('#status').textContent.includes('1 favori'));assert.equal(d.querySelectorAll('.card').length,1);d.querySelector('#showRecent').click();await wait(()=>d.querySelector('#status').textContent.includes('récent'));assert.equal(d.querySelectorAll('.card').length,1);w.localStorage.setItem('bible-qsse-page-fixture','2');backup=await w.BibleBackup.build();assert.equal(backup.version,1);assert.equal(backup.tags.length,2);assert.equal(backup.documents.length,1);assert.equal(backup.positions['bible-qsse-page-fixture'],'2');
  dom.window.close();dom=app();w=dom.window;d=w.document;await wait(()=>d.querySelectorAll('.categoryCard').length===2);d.querySelector('.categoryCard .openDoc').click();await wait(()=>d.querySelectorAll('.tagChip').length===2);assert.match(d.querySelector('#indexStatus').textContent,/3 PDF indexé/);
  w.showDirectoryPicker=async()=>other;d.querySelector('#choose').click();await wait(()=>d.querySelectorAll('.categoryCard').length===1&&d.querySelectorAll('.tagChip').length===0);assert.match(d.querySelector('#indexStatus').textContent,/Indexe les PDF/);
  w.showDirectoryPicker=async()=>primary;d.querySelector('#choose').click();await wait(()=>d.querySelectorAll('.categoryCard').length===2);d.querySelector('.categoryCard .openDoc').click();await wait(()=>d.querySelectorAll('.tagChip').length===2);
  manual.contents='Nouveau texte';manual.modified=2;d.querySelector('#search').value='evacuation';d.querySelector('#search').dispatchEvent(new w.Event('input'));await wait(()=>d.querySelector('#status').textContent.startsWith('0 résultat'));
  d.querySelector('#search').value='';d.querySelector('#search').dispatchEvent(new w.Event('input'));await wait(()=>d.querySelector('.tagEdit:not(.deleteEntry)'));d.querySelector('.tagEdit:not(.deleteEntry)').click();d.querySelector('#tagInput').value='';d.querySelector('#tagForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait(()=>!d.querySelector('#tagDialog').open&&d.querySelectorAll('.tagChip').length===0);await w.BibleBackup.restore(backup);await wait(()=>d.querySelectorAll('.tagChip').length===2);
  dom.window.close();primary.permissionState='prompt';dom=app();w=dom.window;d=w.document;await wait(()=>d.querySelector('#choose').textContent.startsWith('Rouvrir'));assert.equal(d.querySelectorAll('.categoryCard').length,0);d.querySelector('#choose').click();await wait(()=>d.querySelectorAll('.categoryCard').length===2);assert.equal(primary.permissionRequests,1,'the saved directory handle is reauthorized without selecting the folder again');
 }finally{dom.window.close();global.structuredClone=nativeClone}
});
