const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const {indexedDB}=require('fake-indexeddb');
const rootPath=path.resolve(__dirname,'..'),dirs=new Map();
class Dir{constructor(id,name,children=[]){this._testDirId=id;this.name=name;this.kind='directory';this.children=children;this.permissionState='granted';this.permissionRequests=0;dirs.set(id,this)}async *entries(){for(const child of this.children)yield[child.name,child]}async queryPermission(){return this.permissionState}async requestPermission(){this.permissionRequests++;this.permissionState='granted';return'granted'}async isSameEntry(other){return this._testDirId===other._testDirId}async removeEntry(name,{recursive=false}={}){const index=this.children.findIndex(child=>child.name===name);if(index<0)throw new DOMException('Absent','NotFoundError');const target=this.children[index];if(target.kind==='directory'&&target.children.length&&!recursive)throw new DOMException('Non vide','InvalidModificationError');this.children.splice(index,1)}}
class FileHandle{constructor(name,contents){this.name=name;this.kind='file';this.contents=contents;this.modified=1}async getFile(){return{name:this.name,type:'application/pdf',size:this.contents.length,lastModified:this.modified,arrayBuffer:async()=>new TextEncoder().encode(this.contents).buffer}}}
const manual=new FileHandle('manuel.pdf','Page une.\nProcédure evacuation et sécurité incendie.'),scan=new FileHandle('scan.pdf','');
const primary=new Dir('one','Bible QSSE',[new Dir('fire','02 - Incendie',[manual,new Dir('sub','Formation',[scan])]),new Dir('security','04 - Sûreté',[new FileHandle('plan.pdf','Plan de sûreté')])]);
const other=new Dir('two','Bible QSSE',[new Dir('health','03 - Santé',[new FileHandle('manuel.pdf','Autre bibliothèque')])]);
const nativeClone=global.structuredClone;
global.structuredClone=value=>{const clone=nativeClone(value);const restore=v=>{if(v&&typeof v==='object'){if(v._testDirId)return dirs.get(v._testDirId);for(const key of Object.keys(v))v[key]=restore(v[key])}return v};return restore(clone)};
const wait=async fn=>{for(let i=0;i<150;i++){if(fn())return;await new Promise(resolve=>setTimeout(resolve,10))}throw new Error('Timed out')};
function app(){const dom=new JSDOM(fs.readFileSync(path.join(rootPath,'index.html'),'utf8'),{url:'https://example.test/Bible-QSSE/',runScripts:'outside-only'}),w=dom.window;w.indexedDB=indexedDB;w.matchMedia=()=>({matches:false});w.showDirectoryPicker=async()=>primary;w.confirm=()=>true;w.scrollTo=()=>{};w.requestAnimationFrame=callback=>{callback();return 1};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.BiblePDF={engine:async()=>({extractText:async(bytes,progress)=>{progress(1,1);return new TextDecoder().decode(bytes).split('\n')}}),open:async(file,options)=>{w.lastOpened={file,options};options.onPage?.(options.startPage);options.onLegacyNotes?.('fixture',[])}};for(const script of ['local-tags.js','library-meta.js','pdf-store.js','app.js'])w.eval(fs.readFileSync(path.join(rootPath,script),'utf8'));return dom}
test('V17: common tags, structured notes, search, direct source opening and persistence',async()=>{
  let dom=app(),w=dom.window,d=w.document,backup;
  try{
    await wait(()=>d.querySelector('.empty'));d.querySelector('#choose').click();await wait(()=>d.querySelectorAll('.categoryCard').length===2);assert.equal(d.querySelector('#resumeCard'),null);assert.equal(d.querySelector('#selectionBar'),null);d.querySelector('.categoryCard .openDoc').click();await wait(()=>d.querySelectorAll('.card').length===2);
    const manualCard=[...d.querySelectorAll('.card')].find(card=>card.querySelector('.name')?.textContent==='manuel.pdf'),favorite=manualCard.querySelector('.favoriteToggle');favorite.click();await wait(()=>favorite.getAttribute('aria-pressed')==='true');assert.equal(manualCard.querySelector('.favoriteToggle'),favorite,'favorite does not rerender or move the list');
    manualCard.querySelector('.tagEdit').click();d.querySelector('#tagInput').value='EcoEntreprise, accidents';d.querySelector('#tagForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait(()=>!d.querySelector('#tagDialog').open&&[...d.querySelectorAll('#documentTagFilters input')].some(input=>input.value==='ecoentreprise'));assert.ok([...d.querySelectorAll('#documentTagFilters input')].some(input=>input.value==='accident'),'simple plural is canonicalized');assert.deepEqual([...d.querySelectorAll('.documentTags .tagChip')].map(node=>node.textContent),['EcoEntreprise','Accident'],'document tags are visible directly below the PDF');
    [...d.querySelectorAll('.folder')].find(button=>button.textContent.includes('04 - Sûreté')).click();await wait(()=>d.querySelector('.name')?.textContent==='plan.pdf');d.querySelector('.tagEdit:not(.deleteEntry)').click();d.querySelector('#tagInput').value='EcoEntreprise';d.querySelector('#tagForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait(()=>!d.querySelector('#tagDialog').open&&d.querySelector('.documentTags .tagChip')?.textContent==='EcoEntreprise');
    let box=[...d.querySelectorAll('#documentTagFilters input')].find(input=>input.value==='ecoentreprise');box.checked=true;box.dispatchEvent(new w.Event('change'));await wait(()=>d.querySelectorAll('.card').length===2);assert.deepEqual([...d.querySelectorAll('.name')].map(node=>node.textContent).sort(),['manuel.pdf','plan.pdf'],'document tag filters are transversal across physical folders');box=[...d.querySelectorAll('#documentTagFilters input')].find(input=>input.value==='accident');box.checked=true;box.dispatchEvent(new w.Event('change'));await wait(()=>d.querySelectorAll('.card').length===1);assert.equal(d.querySelector('.name').textContent,'manuel.pdf','multiple document tags use AND filtering');assert.match(d.querySelector('#documentTagsFilter summary').textContent,/Tags \(2\)/);d.querySelector('#showFavorites').click();await wait(()=>d.querySelectorAll('.card').length===1);assert.equal(d.querySelector('.name').textContent,'manuel.pdf','tag filters combine with favorites');d.querySelector('#clearDocumentTags').click();d.querySelector('#showAll').click();await wait(()=>d.querySelectorAll('.categoryCard').length===2);
    d.querySelector('#quickFilter').value='evacuation';d.querySelector('#quickFilter').dispatchEvent(new w.Event('input'));await new Promise(resolve=>setTimeout(resolve,180));assert.match(d.querySelector('#status').textContent,/^0 résultat/);assert.equal(d.querySelector('#search').value,'');d.querySelector('#quickFilter').value='';d.querySelector('#quickFilter').dispatchEvent(new w.Event('input'));d.querySelector('#indexPdfs').click();await wait(()=>d.querySelector('#indexStatus').textContent.includes('OCR nécessaire'));d.querySelector('#quickFilter').value='evacuation';d.querySelector('#contentSearch').click();await wait(()=>d.querySelector('#status').textContent.startsWith('1 résultat'));assert.match(d.querySelector('.searchExcerpt').textContent,/page 2/);
    d.querySelector('.openDoc').click();await wait(()=>w.lastOpened);assert.equal(w.lastOpened.options.startPage,2);w.lastOpened.options.onCreateNote({page:2});assert.equal(d.querySelector('#pdfNoteDialog').open,true);assert.ok([...d.querySelectorAll('#pdfNoteTags input')].some(input=>input.value==='ecoentreprise'),'document-created tags are offered to notes');d.querySelector('#pdfNoteTitle').value='Durée maximale du travail';d.querySelector('#pdfNoteForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait(()=>!d.querySelector('#pdfNoteDialog').open);
    w.lastOpened.options.onCreateNote({page:2});d.querySelector('#pdfNoteTitle').value='Déclaration des accidents';d.querySelector('#pdfNoteText').value='À vérifier lors de la planification.';d.querySelector('#pdfNoteNewTag').value='accident, EPI';d.querySelector('#pdfNoteForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait(()=>!d.querySelector('#pdfNoteDialog').open);
    d.querySelector('#showNotes').click();await wait(()=>d.querySelectorAll('.noteCard').length===2);assert.match(d.querySelector('#status').textContent,/2 note/);d.querySelector('#noteSearch').value='planification';d.querySelector('#noteSearch').dispatchEvent(new w.Event('input'));await wait(()=>d.querySelectorAll('.noteCard').length===1);assert.equal(d.querySelector('.noteTitle').textContent,'Déclaration des accidents');d.querySelector('#noteSearch').value='';d.querySelector('#noteSearch').dispatchEvent(new w.Event('input'));await wait(()=>d.querySelectorAll('.noteCard').length===2);
    for(const key of ['accident','epi']){const box=[...d.querySelectorAll('#noteTagChoices input')].find(input=>input.value===key);box.checked=true;box.dispatchEvent(new w.Event('change'))}await wait(()=>d.querySelectorAll('.noteCard').length===1);assert.equal(d.querySelector('.noteTitle').textContent,'Déclaration des accidents','multiple note tags use AND filtering');d.querySelector('#clearNoteTags').click();await wait(()=>d.querySelectorAll('.noteCard').length===2);
    [...d.querySelectorAll('.noteCard')].find(card=>card.querySelector('.noteTitle').textContent==='Durée maximale du travail').querySelector('.noteOpen').click();await wait(()=>w.lastOpened.options.startPage===2);assert.equal(w.lastOpened.file.name,'manuel.pdf');
    d.querySelector('#showNotes').click();await wait(()=>d.querySelectorAll('.noteCard').length===2);const declaration=[...d.querySelectorAll('.noteCard')].find(card=>card.querySelector('.noteTitle').textContent==='Déclaration des accidents');declaration.querySelector('.noteActions button').click();d.querySelector('#pdfNoteTitle').value='Déclaration accident modifiée';d.querySelector('#pdfNoteForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait(()=>[...d.querySelectorAll('.noteTitle')].some(node=>node.textContent.includes('modifiée')));const beforeFiles=primary.children[0].children.length;[...d.querySelectorAll('.noteCard')].find(card=>card.querySelector('.noteTitle').textContent.includes('modifiée')).querySelector('.noteActions button:last-child').click();await wait(()=>d.querySelectorAll('.noteCard').length===1);assert.equal(primary.children[0].children.length,beforeFiles,'deleting a note never deletes its PDF');
    w.localStorage.setItem('bible-qsse-page-fixture','2');backup=await w.BibleBackup.build();assert.equal(backup.version,2);assert.equal(backup.notes.length,1);assert.ok(backup.tagCatalog.some(tag=>tag.name==='EcoEntreprise'));assert.equal(backup.documents.length,1);assert.equal(backup.positions['bible-qsse-page-fixture'],'2');
    dom.window.close();dom=app();w=dom.window;d=w.document;await wait(()=>d.querySelectorAll('.categoryCard').length===2);d.querySelector('#showNotes').click();await wait(()=>d.querySelectorAll('.noteCard').length===1);assert.equal(d.querySelector('.noteTitle').textContent,'Durée maximale du travail');
    w.showDirectoryPicker=async()=>other;d.querySelector('#choose').click();await wait(()=>d.querySelectorAll('.categoryCard').length===1);d.querySelector('#showNotes').click();await wait(()=>d.querySelectorAll('.noteCard').length===0);await w.BibleBackup.restore(backup);assert.equal(d.querySelectorAll('.noteCard').length,1,'backup restores notes into the selected library');w.showDirectoryPicker=async()=>primary;d.querySelector('#choose').click();await wait(()=>d.querySelectorAll('.categoryCard').length===2);
    dom.window.close();primary.permissionState='prompt';dom=app();w=dom.window;d=w.document;await wait(()=>d.querySelector('#choose').textContent.startsWith('Rouvrir'));d.querySelector('#choose').click();await wait(()=>d.querySelectorAll('.categoryCard').length===2);assert.equal(primary.permissionRequests,1)
  }finally{dom.window.close();global.structuredClone=nativeClone}
});
