const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');

const root=path.resolve(__dirname,'..');

test('a saved area annotation is rendered above the PDF page',async()=>{
  const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://example.test/Bible-QSSE/',runScripts:'outside-only'});
  const {window}=dom;
  const viewport={width:480,height:680,scale:1,userUnit:1,convertToViewportPoint:(x,y)=>[x,680-y],convertToPdfPoint:(x,y)=>[x,680-y]};
  const page={getViewport:()=>viewport,render:()=>({promise:Promise.resolve()}),getTextContent:async()=>({items:[]}),cleanup:()=>{}};
  const document={numPages:1,getPage:async()=>page,destroy:async()=>{}};
  window.HTMLDialogElement.prototype.showModal=function(){this.open=true};
  window.HTMLDialogElement.prototype.close=function(){this.open=false};
  window.HTMLCanvasElement.prototype.getContext=()=>({});
  window.confirm=()=>true;
  window.HTMLElement.prototype.scrollIntoView=()=>{};
  window.HTMLElement.prototype.setPointerCapture=()=>{};
  window.IntersectionObserver=class{observe(){}disconnect(){}};
  window.requestAnimationFrame=callback=>{callback();return 1};
  let saved=[{id:'saved',type:'highlight',page:1,color:'yellow',rects:[[45,560,350,582]]}];
  window.PDFStore={annotations:async()=>structuredClone(saved),saveAnnotations:async(_fingerprint,items)=>{saved=structuredClone(items)}};
  window.__fakeEngine={fingerprint:async()=>"fixture",loadDocument:async()=>document,pdfRect:(_viewport,rect)=>{const a=[rect[0],680-rect[1]],b=[rect[2],680-rect[3]];return [Math.min(a[0],b[0]),Math.min(a[1],b[1]),Math.max(a[0],b[0]),Math.max(a[1],b[1])]},pdfjs:{TextLayer:class{constructor({container}){this.container=container}async render(){const span=window.document.createElement('span');span.textContent='Prevention incendie et evacuation';span.getClientRects=()=>[{left:45,top:100,right:350,bottom:118}];this.container.append(span)}}}};
  let source=fs.readFileSync(path.join(root,'pdf-viewer-v10.js'),'utf8');
  source=source.replace(/^  const engine=.*$/m,"  const engine=()=>Promise.resolve(window.__fakeEngine);");
  window.eval(source);
  await window.BiblePDF.open({name:'demo.pdf',arrayBuffer:async()=>new ArrayBuffer(8)},{searchQuery:'incendie',searchPage:1,searchPages:['Prévention incendie puis contrôle incendie']});
  assert.ok(window.document.querySelector('.pdfSearchHit'),'the matching text is temporarily identified');
  const mark=window.document.querySelector('.pdfMark');
  assert.ok(mark,'the stored annotation creates a mark element');
  assert.equal(mark.style.left,'45px');
  assert.equal(mark.style.top,'98px');
  assert.equal(mark.style.width,'305px');
  assert.equal(mark.style.height,'22px');
  assert.equal(mark.style.backgroundColor,'rgb(255, 224, 51)');
  assert.equal(mark.parentElement.className,'pdfMarks');
  window.document.querySelector('#pdfFind').click();const searchInput=window.document.querySelector('#pdfSearchInput');searchInput.value='incendie';searchInput.dispatchEvent(new window.Event('input'));for(let i=0;i<40&&!window.document.querySelector('#pdfSearchCount').textContent.includes('/ 2');i++)await new Promise(resolve=>setTimeout(resolve,10));assert.equal(window.document.querySelector('#pdfSearchCount').textContent,'1 / 2','local PDF search counts occurrences');assert.ok(window.document.querySelector('.pdfSearchHit'),'local PDF search highlights the result temporarily');window.document.querySelector('#pdfSearchNext').click();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(window.document.querySelector('#pdfSearchCount').textContent,'2 / 2','next navigates to the following occurrence');window.document.querySelector('#pdfSearchClose').click();assert.equal(window.document.querySelectorAll('.pdfSearchHit').length,0,'closing local search removes only temporary highlighting');assert.equal(saved.length,1,'local search never creates an annotation');
  assert.equal(window.document.querySelector('#pdfPen'),null,'the handwritten mode is removed from V16');
  assert.equal(window.document.querySelector('#pdfEraser'),null,'the handwritten eraser is removed from V16');
  const pageNode=window.document.querySelector('.pdfPage'),draw=pageNode.querySelector('.pdfDraw');
  pageNode.getBoundingClientRect=draw.getBoundingClientRect=()=>({left:0,top:0,right:480,bottom:680,width:480,height:680});
  const pointer=(name,x,y,type='pen')=>{const event=new window.MouseEvent(name,{bubbles:true,cancelable:true,button:0,clientX:x,clientY:y});Object.defineProperties(event,{pointerId:{value:1},pointerType:{value:type}});draw.dispatchEvent(event)};
  window.document.querySelector('#pdfHighlight').click();
  pointer('pointerdown',60,108);await new Promise(resolve=>setTimeout(resolve,0));
  pointer('pointermove',260,108);pointer('pointerup',310,108);
  for(let i=0;i<20&&(saved.length<2||window.document.querySelectorAll('.pdfMark').length<2);i++)await new Promise(resolve=>setTimeout(resolve,5));
  assert.equal(saved.length,2,'the direct stroke is saved as a second annotation');
  assert.ok(saved[1].rects[0][2]>saved[1].rects[0][0]);
  assert.equal(window.document.querySelectorAll('.pdfMark').length,2,'the new annotation is immediately visible');
  let requestedPage=0,notes=[];await window.BiblePDF.open({name:'demo.pdf',arrayBuffer:async()=>new ArrayBuffer(8)},{notes,onCreateNote:({page})=>requestedPage=page,onDeleteNote:async note=>notes=notes.filter(item=>item.id!==note.id)});const scroll=window.document.querySelector('#pdfScroll');scroll.scrollTop=237;scroll.scrollLeft=19;window.document.querySelector('#pdfNote').click();assert.equal(requestedPage,1,'+ Note captures the current PDF page without changing it');window.dispatchEvent(new window.Event('resize'));await new Promise(resolve=>setTimeout(resolve,300));assert.equal(scroll.scrollTop,237,'the Android keyboard resize does not rebuild or move the PDF while the note editor is open');notes=[{id:'note-1',title:'Travail de nuit',text:'Conditions applicables au personnel',documentKey:'demo',documentName:'demo.pdf',page:1,tags:['Planification']}];window.BiblePDF.finishNote(notes);assert.equal(scroll.scrollTop,237,'saving a note restores the exact PDF scroll position');assert.equal(window.document.querySelectorAll('.pdfMark').length,2,'creating a note does not remove highlights');assert.equal(window.document.querySelector('.pdfStructuredNote strong').textContent,'Travail de nuit','the structured note appears immediately in Annotations');assert.match(window.document.querySelector('.pdfStructuredNote').textContent,/Planification/);
  window.document.querySelector('#pdfZoom').value='1.5';window.document.querySelector('#pdfZoom').dispatchEvent(new window.Event('change'));await new Promise(resolve=>setTimeout(resolve,20));assert.equal(window.document.querySelectorAll('.pdfMark').length,2,'highlights survive zoom');
  await window.BiblePDF.open({name:'demo.pdf',arrayBuffer:async()=>new ArrayBuffer(8)},{notes,onDeleteNote:async note=>notes=notes.filter(item=>item.id!==note.id)});
  assert.equal(window.document.querySelectorAll('.pdfMark').length,2,'both annotations remain visible after reopening');
  assert.equal(window.document.querySelectorAll('.pdfStructuredNote').length,1,'the structured note remains visible after reopening');
  window.document.querySelector('.pdfStructuredNote button:last-child').click();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(window.document.querySelectorAll('.pdfStructuredNote').length,0,'deleting a note removes it from Annotations');assert.equal(saved.length,2,'deleting a note never deletes a highlight');
  notes=[{id:'note-2',title:'Note indépendante',text:'Toujours présente',documentKey:'demo',documentName:'demo.pdf',page:1,tags:[]}];window.BiblePDF.updateNotes(notes);const highlightEntry=[...window.document.querySelectorAll('#pdfAnnotations li')].find(item=>!item.classList.contains('pdfStructuredNote'));highlightEntry.querySelector('button:last-child').click();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(saved.length,1,'deleting one highlight changes only PDF annotations');assert.equal(window.document.querySelectorAll('.pdfStructuredNote').length,1,'deleting a highlight never deletes a structured note');
  dom.window.close();
});
